### ISSUE TITLE
Error in using the application

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/event-collect#16]
On running `python scrape_eventbrite.py tech` or `python scrape_eventbrite.py "tech"`
```
C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms>scrape_eventbrite.py "tech"
C:\Python27\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 119 of the file C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Following events were found:
Traceback (most recent call last):
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 119, in <module>
    eventCollector(query)
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 113, in eventCollector
    scrapeEvents(events, query)
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 66, in scrapeEvents
    json_data = requests.get(LOKLAK_API_ENDPOINT, params = {'url':url}).json()['data']
  File "C:\Python27\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
C:\Python27\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 119 of the file C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Following events were found:
Traceback (most recent call last):
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 119, in <module>
    eventCollector(query)
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 113, in eventCollector
    scrapeEvents(events, query)
  File "C:\Users\Dell\Downloads\event-collect-master\event-collect-master\platforms\scrape_eventbrite.py", line 66, in scrapeEvents
    json_data = requests.get(LOKLAK_API_ENDPOINT, params = {'url':url}).json()['data']
  File "C:\Python27\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

@niranjan94 Please let me know if I am wrong at any step or is the app not working write now. Thanks !

**Comment by tabesin** [comment]
Does event-collect work in a windows environment? Anyway, does your local python environment support beautifulsoup scrapers?
